name: "broken2"

on:
  push:
    tags:
      - "test2-*"

jobs:
  push:
    runs-on: "ubuntu-latest"
    env:
      TEST_IMAGE_NAME: ghcr.io/zenexer/docker-bug-test:broken2

    steps:
      - uses: "actions/checkout@v2"
      - uses: "docker/setup-qemu-action@v1"
      - uses: "docker/setup-buildx-action@v1"

      - name: "login"
        run: |
          echo '${{ secrets.GITHUB_TOKEN }}' | docker login ghcr.io -u '${{ github.actor }}' --password-stdin

      - name: "build"
        if: "github.event_name != 'pull_request'"
        run: |
          docker buildx build \
            --build-arg SOMETHING=something \
            --tag ${TEST_IMAGE_NAME} \
            --push \
            .
