name: "working2"

on:
  push:
    tags:
      - "test2"

jobs:
  push:
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v2"
      - uses: "docker/setup-qemu-action@v1"
      - uses: "docker/setup-buildx-action@v1"

      - name: "login"
        uses: "docker/login-action@v1"
        with:
          registry: "ghcr.io"
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: "build"
        if: "github.event_name != 'pull_request'"
        run: |
          docker buildx build \
            --tag ghcr.io/zenexer/docker-bug-test:working2 \
            --push \
            .
