name: "working"

on:
  push:
    branches:
      - "main"

jobs:
  push:
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v2"
      - uses: "docker/setup-qemu-action@v1"
      - uses: "docker/setup-buildx-action@v1"

      - name: "login"
        uses: "docker/login-action@v1"
        with:
          registry: "ghcr.io"
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: "build1"
        uses: "docker/build-push-action@v2"
        with:
          context: "."
          platforms: "linux/amd64"
          push: ${{ github.event_name != 'pull_request' }}
          tags: "ghcr.io/zenexer/docker-bug-test:working"

      - name: "build2"
        uses: "docker/build-push-action@v2"
        with:
          context: "."
          platforms: "linux/arm64"
          push: ${{ github.event_name != 'pull_request' }}
          tags: "ghcr.io/zenexer/docker-bug-test:working"
